### PR TITLE
Check package-lock.json and npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by thundron**
Change-type: patch
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

### CODE REVIEW

**Comment by lurch** [comment]
Looks like this fixes #103 ? :smiley:

**Comment by nazrhom** [comment]
@thundron the changes looks good. I would only add a test case for it in https://github.com/balena-io/versionist/blob/master/tests/presets.spec.js#L710

**Comment by lurch** [comment]
Would a project ever have _both_ a `npm-shrinkwrap.json` and a `package-lock.json` (if so, should there be a test for that too?), or are they effectively mutually exclusive?

**Comment by thundron** [comment]
@lurch There's no reason to have both afaik, they serve different purposes wrt dependencies:
`npm-shrinkwrap.json` is used to respect deep sub-dependencies too and is published to `npm` as well, whereas `package-lock.json` is not and just respects top-level dependencies.
The shrinkwrap file is also compatible with older versions of npm
You can find more [here](https://stackoverflow.com/questions/44258235/what-is-the-difference-between-npm-shrinkwrap-json-and-package-lock-json)

**Pull request merged**
